#!/bin/bash
outputdir=$2 maxthreads=$3 numbuckets=$4

if [ ! -d "$outputdir" ]; then
	echo "Diretoria para output nao existe"
	exit 1
else
	if [ "$(ls -A $outputdir)" ]; then
		rm $outputdir/*.txt
	fi
fi

for file in "$1"/*.txt
do
	echo "InputFile=$(basename $file) NumThreads=1"
	./tecnicofs-nosync $file $outputdir/$(basename ${file%.*})-1.txt 1 1 | awk 'END {print}' 
	echo
	for i in $(seq 2 $maxthreads)
	do
		echo "InputFile=$(basename $file) NumThreads=$i"
		./tecnicofs-mutex $file $outputdir/$(basename ${file%.*})-$i.txt $i $numbuckets | awk 'END {print}'
		echo
	done
done

